openapi: 3.0.3
info:
  title: Banking API Specification for account operations
  description: |-
    A simple banking API that allows two operations:
    - get account balance given account number
    - deposit amount to a account 
  version: 1.0-SNAPSHOT
# servers:
#   - url: https://testenvironment.org/api/v1
#   - url: https://prodenvironment.org/api/v1
tags:
  - name: accounts
    description: Operations between bank accounts
paths:
  /account/{accountNumber}:
    get:
      tags:
        - accounts
      summary: Get account information
      description: Get account information using account number
      operationId: getAccount
      parameters:
        - in: path
          name: accountNumber
          schema: 
            type: string
          required: true
          description: Unique account number associated with the account
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        404:
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountNotFoundError'
  /account/deposit:
    post:
      tags:
        - accounts
      summary: Deposit amount to account
      description: Initiates a deposit operation of a desired amount to the account specified 
      operationId: depositToAccount
      requestBody:
        description: Account number and desired amount to deposit
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositRequest'
        required: true
      responses:
        204:
          description: Success
        404:
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountNotFoundError'
components:
  schemas:
    Account:
      type: object
      properties:
        accountNumber:
          type: string
          x-field-extra-annotation: "@org.springframework.data.annotation.Id"
        balance:
          type: number
    AccountNotFoundError:
      type: object
      properties:
        message:
          type: string
    DepositRequest:
      type: object
      properties:
        accountNumber:
          type: string
        depositAmount:
          type: number